eggjs/egg-logger

- lib/egg/context_logger.js
- test/lib/egg/context_logger.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eggjs/egg-logger/5)
> fix: add missing write function on context logger

- .gitignore
- lib/logger.js
- test/lib/egg/error_logger.test.js
- test/lib/egg/logger.test.js
ref [egg/egg-logger!8](https://github.com/eggjs/egg-logger/pull/8)
> feat: add .unredirect() for logger

- benchmark/file_buffer.js
- benchmark/format.js
- benchmark/format_buffer_vs_string.js
- lib/transports/file.js
- lib/transports/file_buffer.js
- lib/transports/transport.js
- lib/utils.js
- test/lib/logger.test.js
- test/lib/transports/transport.test.js
Add a max buffer limit to file buffer logger
> improve: don't convert utf8 string to buffer

- lib/egg/logger.js
- lib/transports/transport.js
- test/fixtures/egg_logger_dynamically.js
- test/lib/egg/logger.test.js
- test/lib/transports/transport.test.js
level can be updated after instantiation
> feat: add level getter to Logger and Transport

- index.d.ts
- package.json
- test/fixtures/egg_ts_logger.ts
- test/lib/transports/file.test.js
- test/lib/ts.test.js
给 egg-logger 添加 d.ts ，从而可以在 egg 的 typings 中直接引入 egg-logger 的 types.
> feat(typings): add typings for egg logger

- index.d.ts
ref: https://cnodejs.org/topic/5b475d32e374eeab6929d66b#5b47ffd1fb9e84ec69cc1a29
> chore(typings): add LoggerOptions['allowDebugAtProd']: boolean

- .eslintignore
- README.md
- README.zh-CN.md
- index.d.ts
- lib/egg/logger.js
- lib/egg/loggers.js
- lib/logger.js
- lib/utils.js
- test/lib/egg/loggers.test.js
- test/lib/logger.test.js
- close https://github.com/eggjs/egg/issues/3288
- close https://github.com/eggjs/egg-logger/pull/36
- treat this issue as a bugfix of https://github.com/eggjs/egg-logger/pull/35, so remove `options`
> feat: support concentrateError and set default to duplicate

- index.d.ts
- test/fixtures/egg_ts_logger.ts
- test/fixtures/tsconfig.json
- test/lib/ts.test.js
fix https://github.com/eggjs/egg-logger/pull/37#issuecomment-449836819
> fix: logger should extend Map

- package.json
https://github.com/eggjs/egg-logger/pull/41#discussion_r244597771
> chore: modify engine version

- lib/utils.js
- test/lib/logger.test.js
> chore: comments typo fix

- lib/transports/file_buffer.js
- test/lib/transports/file.test.js
- test/lib/transports/file_buffer.test.js
> fix: buffer error flush

- lib/transports/file.js
- lib/transports/file_buffer.js
- pick https://github.com/eggjs/egg-logger/pull/30
- better than https://github.com/eggjs/egg-logger/pull/56
> fix: buffer error flush by pick #30

- index.d.ts
> fix(backport): implicitly any type

- benchmark/format_buffer_vs_string.js
- lib/utils.js
- test/lib/formatter.test.js
benchmark add more node version
> refactor: new Buffer() API refactor

- lib/utils.js
- package.json
- test/lib/formatter.test.js
> feat: logger formatError should support FrameworkErrorFormater

- index.d.ts
- test/fixtures/egg_ts_logger.ts
- test/lib/ts.test.js
fix EggLoggers constructor typing
> fix: EggLoggers constructor typing

- .github/workflows/nodejs.yml
- lib/transports/file.js
- package.json
- test/lib/transports/file.test.js
> 🐛 FIX: Ignore error log after stream close on unittest env

- index.d.ts
- lib/egg/loggers.js
- test/lib/egg/loggers.test.js
- test/lib/egg/loggers_with_localStorage.test.js
> 🐛 FIX: Add localStorage options to EggLoggers

- index.d.ts
- index.test-d.ts
- lib/egg/logger.js
- lib/logger.js
- lib/transports/transport.js
- lib/utils.js
- package.json
- test/lib/egg/loggers_with_localStorage.test.js
and fixed paddingMessage missing on contextFormatter(meta)
> feat: allow custom format paddingMessage

- lib/egg/loggers.js
> fix: use util.debuglog instead of debug module

- index.d.ts
- index.test-d.ts
> feat: export logger.options type

- index.d.ts
- lib/egg/logger.js
- lib/transports/transport.js
- lib/utils.js
- test/lib/egg/error_logger.test.js
- test/lib/egg/logger.test.js
- test/lib/formatter.test.js
支持将日期格式化为 ISO 标准格式
Resolves https://github.com/eggjs/egg/issues/5145
`dateISOFormat = true` 时，将使用 `new Date(). toISOString()` 输出日期
> feat: add dateISOFormat option

- .github/workflows/codeql.yml
- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- index.d.ts
- index.test-d.ts
- package.json
> fix: allow EggConsoleLogger init without options

- lib/egg/console_logger.js
- lib/egg/logger.js
- lib/transports/transport.js
- lib/utils.js
- test/lib/egg/error_logger.test.js
- test/lib/utils.test.js
> feat: print err.cause if exists
